### ISSUE TITLE
TOOL: github username vs ID

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/summit-2025#12]
Small tool that check if the usernames in the teams repo still matched their IDs (so we don't need to track people with an integer, but can keep using the username relatively safely).

I suppose this should be run on a cron and email org owners when a discrepancy appears

**Comment by bsipocz** [comment]
Given Sanket's username change such a tool could have been useful to pick up discrepancies between the different lists, too.

**Comment by jarrodmillman** [comment]
We should look at https://github.com/eclipse-csi/otterdog
